#!/bin/bash
# Manual test script for IRC modes and channel management

echo "=== IRC Modes & Channel Management Test ==="
echo ""
echo "This script will guide you through testing the new features."
echo "You will need to open 3 terminal windows."
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Terminal 1: Start IRC Server ==="
echo "Run: ./gradlew :server:run"
echo ""
echo "Wait for: 'IRC Server started on port 6667'"
echo ""
echo "Press Enter when server is running..."
read

echo ""
echo "=== Terminal 2: Connect as Alice ==="
echo "Run: telnet localhost 6667"
echo ""
echo "Then type:"
echo "  NICK alice"
echo "  USER alice 0 * :Alice User"
echo "  JOIN #test"
echo ""
echo "Alice should now be in #test and automatically have operator status (@)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Terminal 3: Connect as Bob ==="
echo "Run: telnet localhost 6667"
echo ""
echo "Then type:"
echo "  NICK bob"
echo "  USER bob 0 * :Bob User"
echo "  JOIN #test"
echo ""
echo "Bob should join #test as a regular user"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 1: Channel Modes ==="
echo ""
echo "In Alice's terminal, test channel modes:"
echo "  MODE #test +m            # Set moderated mode"
echo "  MODE #test               # Query current modes"
echo ""
echo "In Bob's terminal:"
echo "  PRIVMSG #test :Hello!    # Should fail (moderated, no voice)"
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +v bob        # Give Bob voice"
echo ""
echo "In Bob's terminal:"
echo "  PRIVMSG #test :Hello!    # Should succeed now"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 2: WHOIS Command ==="
echo ""
echo "In Alice's terminal:"
echo "  WHOIS bob"
echo ""
echo "Should show:"
echo "  - Bob's username and hostname"
echo "  - Channels bob is in (#test with + for voice)"
echo "  - Server information"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 3: KICK Command ==="
echo ""
echo "In Alice's terminal:"
echo "  KICK #test bob Being too loud"
echo ""
echo "Bob should be removed from #test"
echo ""
echo "In Bob's terminal, rejoin:"
echo "  JOIN #test"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 4: Channel Key ==="
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +k secretpass"
echo "  KICK #test bob          # Kick bob again"
echo ""
echo "In Bob's terminal:"
echo "  JOIN #test              # Should fail (no key)"
echo "  JOIN #test wrongpass    # Should fail (wrong key)"
echo "  JOIN #test secretpass   # Should succeed"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 5: Ban Management ==="
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +b bob!*@*   # Ban bob's nickname"
echo "  MODE #test +b           # List bans"
echo "  KICK #test bob Banned"
echo ""
echo "In Bob's terminal:"
echo "  JOIN #test              # Should fail (banned)"
echo ""
echo "In Alice's terminal:"
echo "  MODE #test -b bob!*@*   # Remove ban"
echo ""
echo "In Bob's terminal:"
echo "  JOIN #test secretpass   # Should succeed now"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 6: INVITE Command ==="
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +i           # Set invite-only"
echo "  KICK #test bob"
echo ""
echo "In Bob's terminal:"
echo "  JOIN #test secretpass   # Should fail (invite only)"
echo ""
echo "In Alice's terminal:"
echo "  INVITE bob #test"
echo ""
echo "In Bob's terminal:"
echo "  JOIN #test secretpass   # Should succeed (invited)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 7: User Modes ==="
echo ""
echo "In Bob's terminal:"
echo "  MODE bob +i             # Set invisible"
echo "  MODE bob                # Query modes (should show +i)"
echo "  MODE bob -i             # Remove invisible"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 8: AWAY Command ==="
echo ""
echo "In Bob's terminal:"
echo "  AWAY :Gone for lunch"
echo ""
echo "In Alice's terminal:"
echo "  WHOIS bob               # Should show away message"
echo ""
echo "In Bob's terminal:"
echo "  AWAY                    # Clear away status"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 9: OPER Command ==="
echo ""
echo "In Bob's terminal:"
echo "  OPER admin adminpass    # Become server operator"
echo ""
echo "Bob should now have +o mode"
echo ""
echo "In Alice's terminal:"
echo "  WHOIS bob               # Should show 'is an IRC operator'"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Test 10: Topic Lock ==="
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +t           # Lock topic to ops only"
echo "  TOPIC #test :Ops only can change this"
echo ""
echo "In Bob's terminal (without ops):"
echo "  MODE #test -o bob       # Alice removes Bob's potential ops"
echo ""
echo "In Bob's terminal:"
echo "  TOPIC #test :New topic  # Should fail (not operator)"
echo ""
echo "In Alice's terminal:"
echo "  MODE #test +o bob       # Re-grant operator"
echo ""
echo "In Bob's terminal:"
echo "  TOPIC #test :New topic  # Should succeed now"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "=== Tests Complete! ==="
echo ""
echo "All major features have been tested:"
echo "  ✓ Channel modes (m, s, i, t, n, k, l)"
echo "  ✓ User modes (i, o)"
echo "  ✓ Operator/voice status"
echo "  ✓ KICK, INVITE, BAN commands"
echo "  ✓ WHOIS, AWAY, OPER commands"
echo "  ✓ Mode enforcement"
echo ""
echo "To stop the server, press Ctrl+C in Terminal 1"
echo ""
